### ISSUE TITLE
Weird inconsistencies between latest BOLDigger3 and BOLD id portal results

### ISSUE THREAD

**Issue by Anto007** [DominikBuchner/BOLDigger3#39]
Hi @DominikBuchner 

I notice that BOLDigger3 2.0.2 classification results are rather weird. See below the screenshot for the same ASV_1 from BOLDigger3 and from the online BOLD database id portal. I've also pasted below the ASV_1 sequence if you would like to check for yourself.

<img width="2232" height="296" alt="Image" src="https://github.com/user-attachments/assets/86a6cb27-7df2-4600-8f76-e533bc7ce76c" />

<img width="2606" height="1814" alt="Image" src="https://github.com/user-attachments/assets/38163859-57a0-49f5-a940-bc1ccd05d379" />

```
>ASV_1
ACTGAGTCATATTACAAGTCACTCAGGAGGTGCTGTAGATTTAGCTATCTTTAGTTTACACGTTTCAGGT
GCAAGTAGTATCTTAGGAGCAATCAATTTTATTACAACCATCTTTAATATGCGTGGACCTGGATTATTAA
TGCACCGATTACCATTATTTGTATGGAGTGTTTTAATTACAGCATTTTTACTTCTTCTCTCATTACCTGT
ACTCGCAGGAGCAATTACAATGCTATTAACCGATCGAAACTTTTCAACCAGTTTCTTTGATCCAAGTGGT
GGAGGAGACCCTATTTTATACCAACATTTATTT
```

**Comment by Anto007** [comment]
Thanks @DominikBuchner This is basically from the same dataset (ASVs.fa) that I had shared with you yesterday. From a quick look, there are other examples of inconsistencies in the same dataset: ASV_33 is classified as Cnidaria by BOLDigger3 but the BOLD id portal classifies it as Haptophyta

**Comment by DominikBuchner** [comment]
Fixed with 2.1.1. There's still some discrepency between the JSONL you can download from the Website and the Table that is actually displayed. We're in contact with BOLD with regard to this issue.

**Comment by Anto007** [comment]
@DominikBuchner Yes, I see that there's still not a 100% overlap between my latest results from v2.1.1 and the web engine. ASV_1 taxonomy is in agreement though but not ASV_33. I hope more clarity will emerge in this regard from your communication with the BOLD admin

**Comment by DominikBuchner** [comment]
Hi there,
fixed with 2.1.2!
best
Dominik
